name: First Work Flow

on:
   push:
   branches: [ main ]
  
  jobs:
      demo:
      runs-on: ubuntu-latest

      steps:
           - name: greetings
           run: echo "Hello I Am a Developer"
  

  
